### ISSUE TITLE
problem with loadin the pretrained weight

### ISSUE THREAD

**Issue by SaharR1372** [HaoHou-98/SCGAN#4]
Thanks for your interesting work, would you please let me know what is the problem with this error? I have load your pretrained weight model but it does not work.
Thanks in advance

RuntimeError: Error(s) in loading state_dict for G_RLS:
	Missing key(s) in state_dict: "layers_set_final.0.0.conv1.weight",.........................................

**Comment by hamedsteiner** [comment]
Based on the code base, I guess the problem is with Gh2l (High-res to low-res)
`a = torch.load('./pretrained_model/pretrained_model.pth')["G_h2l"]`, which should be changed to 
`b = torch.load('./pretrained_model/pretrained_model.pth')["G_l2h"]`.
Prior to that I though the problem is with mu cuda version, etc.

**Comment by HaoHou-98** [comment]
> Based on the code base, I guess the problem is with Gh2l (High-res to low-res) `a = torch.load('./pretrained_model/pretrained_model.pth')["G_h2l"]`, which should be changed to `b = torch.load('./pretrained_model/pretrained_model.pth')["G_l2h"]`. Prior to that I though the problem is with mu cuda version, etc.

Thank you for the solution, and I will explain it in the README.md.
